Add controllers
alexhved/java-shareit pull request #1
Opened 2022-11-23 13:45 UTC by alexhved

initial pull request

2022-11-24 12:56 UTC, sergeymamonov requested changes

2022-11-24 12:56 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/error/ResourceNotFoundException.java
> +    private String message;
Это поле в классе не нужно, так как оно не используется. Аналогично и для других классов ошибок.

2022-11-24 12:56 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        return result.stream().collect(Collectors.toUnmodifiableList());
Писать сначала во множество, а потом переписывать в массив очень затратно и по времени и по памяти. Если это сделано, чтобы отсеить одну и ту же запись, которая попала в выборки и по имени и по описанию, так можно сделать один if на строке 113, а в нем сделать два условия через || (одно со строк 113-114, а второе условие со строк 116-117).

2022-11-24 18:48 UTC, alexhved commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        return result.stream().collect(Collectors.toUnmodifiableList());
Всё верно, спасибо за подсказки

2022-11-24 18:49 UTC, alexhved commented
Замечания исправлены, спасибо за ревью!

2022-11-25 17:23 UTC, sergeymamonov approved these changes

2022-11-25 17:23 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                .forEach(item -> {
попробуйте еще
.filter()
.collect()

2022-12-01 08:17 UTC, merged