Add bookings
alexhved/java-shareit pull request #2
Opened 2022-12-14 19:38 UTC by alexhved

2022-12-15 19:00 UTC, sergeymamonov requested changes

2022-12-15 19:00 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking() {
Можно воспользоваться аннотацией Lombok.

2022-12-15 19:00 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public static BookingBuilder builder() {
Этот код и весь код ниже который относится к билдеру можно не писать, а заменить одной аннотацией @Builder.

2022-12-15 19:00 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/model/User.java
>      private long id;
Сначала лучше в классе размещать поля, а потом уже методы.

2022-12-15 19:00 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserValidator.java
>      private void checkEmailOnDuplicate(String email) {
Этот метод где-то используется?

2022-12-15 19:00 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +    name VARCHAR NOT NULL,
Размер VARCHAR должен быть ограничен.

2022-12-16 15:30 UTC, alexhved commented
Исправлены замечания

2022-12-16 18:10 UTC, sergeymamonov approved these changes

2022-12-18 12:00 UTC, merged